# -*- coding: utf-8 -*-
"""Proyecto_aspiradora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpciQ3acKyo7dENADkFopwjhPt6KhtDK

# Declaracion de variables
"""

HABITACION_SUCIA = 1
HABITACION_LIMPIA = 0

estado_habitaciones = [HABITACION_SUCIA, HABITACION_LIMPIA, HABITACION_SUCIA]

posicion_robot = 0
total_limpiezas = 0
meta_limpiezas = 2

"""# Accion de la aspiradora"""

def mover_a(destino):
    global posicion_robot
    posicion_robot = destino
    print("Robot se mueve a habitacion", posicion_robot)


def aspirar_actual():
    global total_limpiezas

    if estado_habitaciones[posicion_robot] == HABITACION_SUCIA:
        estado_habitaciones[posicion_robot] = HABITACION_LIMPIA
        total_limpiezas += 1
        print("Aspirando habitacion", posicion_robot)
    else:
        print("Habitacion ya limpia")


def detener_robot():
    print("Meta alcanzada")

def decidir_accion(destino_si_limpia):
    if estado_habitaciones[posicion_robot] == HABITACION_SUCIA:
        aspirar_actual()
    else:
        mover_a(destino_si_limpia)

def repetir_acciones(veces):
    for i in range(veces):
        print("Repeticion", i + 1)
        siguiente_habitacion = (posicion_robot + 1) % len(estado_habitaciones)
        decidir_accion(siguiente_habitacion)

def caso_prueba_if():
    global posicion_robot
    print("\n--- CASO IF SUCIO ---")

    posicion_robot = 0
    decidir_accion(1)
    decidir_accion(2)

caso_prueba_if()

def caso_prueba_repeat():
    global posicion_robot
    print("\n--- CASO REPEAT ---")

    posicion_robot = 0
    repetir_acciones(5)

caso_prueba_repeat()

if total_limpiezas >= meta_limpiezas:
    detener_robot()
else:
    print("Meta aun no alcanzada")